name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.14.3
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 6.2
          auto-start: "true"
      - name: Run tests
        run: |
          deno test --allow-net --import-map=import_map.json